[package]
name = "sea-entities"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sea-orm = {workspace = true}
time = {workspace = true}
serde = {workspace = true}