[package]
name = "app"
version = "0.1.0"
edition = "2021"

[lib]
name = "app"
crate-type = ["cdylib", "rlib"]

[dependencies]
# server
server-setup = {path = "../server-setup", optional = true}
tokio = { workspace=true, optional = true }

leptos_axum = { workspace=true, optional = true }

# client
console_error_panic_hook = {version="0.1", optional=true}
tracing-web = {version="0.1.2", optional=true}
wasm-bindgen = {version="=0.2.87", optional=true}
time = {workspace=true, optional = true}

# shared
backend = {path = "../backend", default-features = false}
leptos = { workspace = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }
cfg-if = "1"
http = "0.2.8"
serde = {workspace = true}
thiserror = "1.0.49"
tracing-subscriber = {version="0.3.17", features=["env-filter"]}

[features]
default = ["ssr","hydrate"]
hydrate = [
    "dep:console_error_panic_hook",
    "dep:tracing-web",
    "dep:wasm-bindgen",
    "tracing-subscriber/time",
    "dep:time",
    "time/wasm-bindgen", # make time work on WASM
    "leptos/hydrate",
    "leptos_meta/hydrate",
    "leptos_router/hydrate",
    "backend/hydrate",
]
ssr = [
    "dep:server-setup",
    "dep:tokio",
    "dep:leptos_axum",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "backend/ssr",
]

[package.metadata.cargo-all-features]
denylist = ["axum", "tokio", "tower", "tower-http", "leptos_axum"]
skip_feature_sets = [["ssr", "hydrate"]]
