[package]
name = "ff-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.57"
quote = "1.0.35"
proc-macro2 = "1.0.79"
proc-macro-error = "1.0.4"

[dev-dependencies]
trybuild = "1.0.90"
bevy_reflect = "0.13.0"

ff-object = {path="../ff-object"}