[package]
name = "ff-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.48"
quote = "1.0.35"
proc-macro2 = "1.0.75"
proc-macro-error = "1.0.4"

[dev-dependencies]
trybuild = "1.0.88"

entities = {path="../entities"}