[package]
name = "ff-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.58"
quote = "1.0.36"
proc-macro2 = "1.0.81"
proc-macro-error = "1.0.4"

[dev-dependencies]
trybuild = "1.0.96"
bevy_reflect = "0.13.2"

ff-object = {path="../ff-object"}