//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

#[cfg(feature = "orm")]
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, bevy_reflect::Reflect)]
#[reflect(from_reflect = false)]
#[cfg_attr(feature="orm", derive(DeriveEntityModel) )]
#[cfg_attr(feature="orm", sea_orm(table_name = "feed") )]
pub struct Model {
	pub url: String,
	pub name: String,
	pub strategy: String,
	#[cfg_attr(feature="orm", sea_orm(primary_key) )]
	pub id: i32,
	#[reflect(ignore)]
	pub created_at: time::PrimitiveDateTime,
	#[reflect(ignore)]
	pub updated_at: time::PrimitiveDateTime,
}


cfg_if::cfg_if! { if #[cfg(feature = "orm")] {


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::entry::Entity")]
	Entry,
	#[sea_orm(has_many = "super::fetch::Entity")]
	Fetch,
}

impl Related<super::entry::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Entry.def()
	}
}

impl Related<super::fetch::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Fetch.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}


}}
