//! `SeaORM` Entity. Modified from something generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "feeds")]
pub struct Model {
    pub url: String,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: TimeDateTime,
    pub updated_at: TimeDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
