name: Test

on:
  # push:
  #  branches: [ "main" ]
  workflow_dispatch:
    
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "SharedTests"
    - name: Run tests
      run: cargo test --verbose
  
  leptos-build:
    name: Cargo leptos build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "SharedTests"
      - name: Get WASM target (& std)
        run: rustup target add wasm32-unknown-unknown
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-leptos
      - name: Build with cargo-leptos
        run: cargo leptos build
